name: adjoint-pdr
version: 0.1.0.0
github: "kotapiku/AdjointPDR"
license: BSD-3-Clause
author: "Mayuko Kori"
maintainer: "ice08235523@gmail.com"
copyright: "2024 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/kotapiku/AdjointPDR#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - Stack
  - sbv < 10 # to use sbvExists

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wno-name-shadowing

library:
  source-dirs: src

benchmarks:
  benchmark-mdp:
    main: bench/BenchmarkMDP.hs
    source-dirs: app
    other-modules: []
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - adjoint-pdr
      - tasty-bench

tests:
  adjoint-pdr-test:
    main: Tasty.hs
    source-dirs: test
    other-modules:
      - MDPTest
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - adjoint-pdr
      - tasty
      - tasty-hunit
    build-tools: tasty-discover:tasty-discover
